<?php 
session_start();
if(isset($_GET['user_id']) && isset($_GET['project_id']))
{
    $key='rzp_test_kdIA1t5Q6LjFzS';
    $_SESSION['freelancer_id'] = $_GET['user_id'];
    $_SESSION['freelancer_project_id']= $_GET['project_id'];
    $total=$_GET['total'];
    $_SESSION['total_pay']=$_GET['total'];
    $cn = mysqli_connect('localhost', 'root', '', 'wws');
    // echo "<script></script>";
    $sql = "select * from user where user_id=".$_GET['user_id'];
    $result=mysqli_query($cn, $sql);
    $row = mysqli_fetch_array($result);


    mysqli_close($cn);


}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="icon" type="image/x-icon" href="../img/logo1.png">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <!-- Vendor CSS Files -->
    <link rel="stylesheet" href="../assets/css/bootstrap4.min.css">
    <link href="../assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="../assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="../assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="../assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="../assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="../assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    <!-- Template Main CSS File -->
    <link href="../assets/css/style.css" rel="stylesheet">
    <style>
        .razorpay-payment-button{
            display: none;
        }
    </style>
</head>
<body>
    <div class="container text-center mt-3">
    <p>Click the button to pay.</p>
    <button onclick="call()" class="btn btn-primary">Pay Now</button>
</div>

    <form action="done_payment.php" id="myForm" method="POST">
        <script
            src="https://checkout.razorpay.com/v1/checkout.js"
            data-key="<?php echo $key;?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
            data-amount="<?php echo $total * 100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
            data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
            data-id="<?php echo 'OID'.rand(10,100);?>"// Replace with the order_id generated by you in the backend.
            data-buttontext="Pay with Razorpay"
            data-name="WWS"
            data-description="Freelancing"
            data-image="http://localhost/wws/img/logo1.png"
            data-prefill.name="<?php echo $row['user_name'];?>"
            data-prefill.email="<?php echo $row['email'];?>"
            data-prefill.contact="<?php echo $row['contact_number'];?>"
            data-theme.color="#F37254"
        ></script>
        <input type="hidden" custom="Hidden Element" name="hidden"/>
    </form>
    <script>
        // Document ready function to execute code when the DOM is fully loaded
        $(document).ready(function() {
            // Trigger click event when the document is ready
            $('.razorpay-payment-button').trigger('click');
        });
        function call()
        {
            $('.razorpay-payment-button').trigger('click');
        }
    </script>
</body>
</html>
